### ISSUE TITLE
Vaccination/Tested/Recovery data

### ISSUE THREAD

**Issue by luzianscherrer** [admin-ch/CovidCertificate-SDK-Android#79]
Does the SDK only expose the generic part of the certificate data or is it also possible to access the vaccination/tested/recovery data? I am referring to the sections as described in https://github.com/admin-ch/CovidCertificate-Examples

**Comment by luzianscherrer** [comment]
I'm also interested if it is possible to access the raw JSON of the certificate. A quick answer would be much appreciated.

**Comment by luzianscherrer** [comment]
Bump

**Comment by goebelUB** [comment]
For the verifier, these details are by design not exposed. Only the minimum amount of data needed to display the verification result (isValid, name, date of birth, etc) is exposed. Hence the [wrapping of the CertificateHolder in a VerificationCertificateHolder](https://github.com/admin-ch/CovidCertificate-SDK-Android/blob/main/sdk/src/main/java/ch/admin/bag/covidcertificate/sdk/android/models/VerifierCertificateHolder.kt).

**Comment by luzianscherrer** [comment]
Ok, thank you. I was primarily asking to be able to distinguish between 2G/3G but I've just noticed that this is now covered in the new version 2.0.
