### ISSUE TITLE
Using this SDK to validate certificates other countries (inside EU)

### ISSUE THREAD

**Issue by siga111** [admin-ch/CovidCertificate-SDK-Android#95]
Greetings!

I work at a company that provides booking management solutions for small businesses. In our business-oriented application we have a QR code scanner to check tickets/reservations. We are considering using the same scanner to validate covid certificates as it would greatly simplify life for the people at the counter and allow customers to pass the check in area much faster, reducing crowds at the entrances.

While researching for existing solutions I have found this repository to be the best solution, but I am not sure about few things:
* Can developers from outside of Switzerland use this SDK directly or is it better to fork it and adapt to use local DCC authority? 
* Do you have any recommendations on implementing support of Latvian DCC authority in a potential fork?

**Comment by luzianscherrer** [comment]
+1

**Comment by goebelUB** [comment]
Sorry for the late reply!

If you want to validate DCCs against the rules that are currently valid in Switzerland, then I believe you can use this SDK even if you are not based in Switzerland. Since EU DCCs are generally valid in Switzerland, this could work.
In that case, as mentioned in the README, you should get in touch with the Federal Office for Public Health to get an app token assigned: Covid-Zertifikat@bag.admin.ch.

However if you want to validate against local rules, it is more complicated. Currently, the SDK is heavily bound to Switzerland. Some examples:
- The backend URLs are hardcoded
- The root certificate used for certificate pinning is also hardcoded
- The backend is assumed to provide the API from the [Verifier-Service](https://github.com/admin-ch/CovidCertificate-App-Verifier-Service)

Thus it will be easiest for you to fork it and go from there. Assuming that your country deployed a fork of our Swiss Verifier-Service as a backend, the changes should be minimal (i.e. different backend URL, different certificate pin). If not, you will need to make larger changes, especially to sdk.android.net.service and sdk.android.repository.

I hope that helps. In fact, there is precedence: the Austria team also [forked](https://github.com/BRZ-GmbH) the Swiss apps and SDKs!

**Comment by siga111** [comment]
Thanks for the response. After I got the specs from Latvian authorities it turned out that it would be easier and cleaner to write similar solution from scratch on top of [kotlin-hcert](https://github.com/ehn-dcc-development/hcert-kotlin). There are just too many differences in implementation details.
If we ever decide to make our implementation public, I will make sure to mention your repository as the main inspiration :)
